# Generated by Django 3.2.25 on 2024-08-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240802_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='referrer',
            new_name='referred_by',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='referred',
            new_name='referred_to',
        ),
        migrations.RemoveField(
            model_name='group',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='moderators',
        ),
    ]
