# Generated by Django 3.2.25 on 2024-08-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240802_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='referral_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
