# Generated by Django 3.2.25 on 2024-08-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_group_referral_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='referral_url',
        ),
    ]
