# Generated by Django 3.2.25 on 2024-08-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20240803_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='waiting_for_approval',
        ),
        migrations.AddField(
            model_name='post',
            name='author_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
