# Generated by Django 3.2.25 on 2024-08-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20240803_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
