# Generated by Django 3.2.25 on 2024-08-04 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_answer_company_notification_question_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='poll_images')),
                ('caption', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('choice1', models.CharField(max_length=255)),
                ('choice2', models.CharField(blank=True, max_length=255, null=True)),
                ('choice3', models.CharField(blank=True, max_length=255, null=True)),
                ('choice1_votes', models.IntegerField(default=0)),
                ('choice2_votes', models.IntegerField(default=0)),
                ('choice3_votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('companies', models.ManyToManyField(blank=True, related_name='polls', to='users.Company')),
                ('sectors', models.ManyToManyField(blank=True, related_name='polls', to='users.Sector')),
            ],
        ),
    ]
