# Generated by Django 3.2.25 on 2024-08-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20240804_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='badge',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='icon_color',
        ),
        migrations.AddField(
            model_name='poll',
            name='community',
            field=models.CharField(default={}, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(default='   ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='community',
            field=models.CharField(default='  ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='   ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='poll',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='polls', to='users.Tag'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='users.Tag'),
        ),
    ]
