# Generated by Django 3.2.25 on 2024-08-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20240806_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
        migrations.AddField(
            model_name='badge',
            name='icon_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
