# Generated by Django 3.2.25 on 2024-08-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_groupaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_model',
            old_name='referral_points',
            new_name='points',
        ),
        migrations.DeleteModel(
            name='GroupAction',
        ),
    ]
