# Generated by Django 3.2.25 on 2024-08-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20240807_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_model',
            old_name='points',
            new_name='referral_points',
        ),
    ]
