# Generated by Django 3.2.25 on 2024-08-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_rename_points_user_model_referral_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_model',
            old_name='referral_points',
            new_name='points',
        ),
    ]
