# Generated by Django 3.2.25 on 2024-08-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_referral_points_user_model_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_model',
            old_name='points',
            new_name='referral_points',
        ),
    ]
