# Generated by Django 3.2.25 on 2024-08-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20240813_0620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionImage',
        ),
    ]
