# Generated by Django 3.2.25 on 2024-08-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_delete_questionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='featured_image',
        ),
    ]
