# Generated by Django 3.2.25 on 2024-08-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20240813_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='community',
        ),
    ]
