# Generated by Django 3.2.25 on 2024-08-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_question_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='community',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
