# Generated by Django 3.2.25 on 2024-08-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_question_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
