# Generated by Django 3.2.25 on 2024-08-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_user_model_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='featured_images',
            field=models.ImageField(null=True, upload_to='featured_images/'),
        ),
    ]
