# Generated by Django 3.2.25 on 2024-08-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_question_featured_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='featured_images',
        ),
        migrations.AddField(
            model_name='question',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='featured_images/'),
        ),
    ]
