# Generated by Django 3.2.25 on 2024-08-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20240815_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/'),
        ),
    ]
