# Generated by Django 3.2.25 on 2024-08-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_question_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='pseudonym',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
