# Generated by Django 3.2.25 on 2024-08-28 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_company_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='parent_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_answers', to='users.answer'),
        ),
    ]
