# Generated by Django 3.2.25 on 2024-09-03 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_company_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ticker',
        ),
        migrations.AddField(
            model_name='post',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_model',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('post', 'user')},
        ),
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.post')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
