# Generated by Django 3.2.25 on 2024-09-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20240906_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
