# Generated by Django 3.2.25 on 2024-09-06 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_user_model_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_model',
            name='referral_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_model',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
