# Generated by Django 3.2.25 on 2024-09-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_user_model_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='referred_by_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
