# Generated by Django 3.2.25 on 2024-09-06 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_user_model_referred_by_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='downvote',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downvotes_records', to='users.question'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvotes_records', to='users.question'),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvote_records', to='users.post'),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='post_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_downvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
