# Generated by Django 3.2.25 on 2024-09-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20240906_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downvote',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downvote_records', to='users.post'),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvote_records', to='users.post'),
        ),
    ]
