# Generated by Django 3.2.25 on 2024-09-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20240906_1214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='downvote',
            unique_together={('question', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('question', 'user')},
        ),
    ]
